### ISSUE TITLE
RZP register does not contain all subjects

### ISSUE THREAD

**Issue by aufi** [strzibny/ruby-ares#3]
This gem cannot find some subjects (e.g. 70890692, 27829383). The reason looks to be use of RZP registry instead of standard registry. STD registry does not contain some informations like DIC (and I am not sure about difference between name and company in gem's Subject class).

If you are open to adjust some Subject's attributes, I can prepare patch.

Dirty changed at https://github.com/aufi/ruby-ares/commit/81710e71cb55479498f2745f4ddec66118a0331e (not worth for pull request for now)

**Comment by strzibny** [comment]
Hi @aufi, I had a pull request opened to change the registry to DARV BAS which is now merged (https://github.com/strzibny/ruby-ares/commit/b01769d1570fe090c84c6feb942fca38edd7bafd). Is this enough for you? If you need STD, I would accept a PR that supports this one as well (but leaving BAS there).

**Comment by aufi** [comment]
Hi, thanks for the update. Current version works good:)
